#!/bin/sh

heroku pg:backups capture --app=neoclassic &&
curl -o latest.dump `heroku pg:backups public-url --app=neoclassic` &&
pg_restore --verbose --clean --no-acl --no-owner -h localhost -Upostgres -d neoclassicdev latest.dump &&
rm latest.dump
